---
name: "JK-BMS wired management"
version: 3.5.1
slug: "smartphoton_jkbms"
description: JK-BMS Management via RS485 & CAN bus or TCP/IP Gateway
url: https://domosimple.eu/forum/thread-917.html
ingress: false
ingress_stream: false
panel_icon: mdi:sitemap
init: false
homeassistant: 2025.10.1
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
privileged:
  - NET_ADMIN
  - SYS_RAWIO
ports:
  "1891/tcp": 1891
ports_description:
  "1891/tcp": Web interface
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
uart: true
map:
  - config:rw
  - media:rw
  - share:rw

options:
  # JK-BMS Configuration
  jkbms_path: "/dev/serial/by-id/usb-xxxx_USB_Serial-abcdefghij"
  jkbms_count: 1
  use_gateway: false
  gateway_ip_port: "192.168.1.100:5000"
  communication_debug: false
  bms_broadcasting: false
  CAN_bus_usage: false

  # MQTT Configuration
  mqttadresse_port: "core-mosquitto.local.hass.io:1883"
  mqttuser: "username"
  mqttpass: "password"

  # Telemetry
  Send_bip: true

schema:
  # JK-BMS Configuration
  jkbms_path: str
  jkbms_count: int(1,15)?
  use_gateway: bool
  gateway_ip_port: str?
  communication_debug: bool
  bms_broadcasting: bool
  CAN_bus_usage: bool

  # MQTT Configuration
  mqttadresse_port: str?
  mqttuser: str?
  mqttpass: password?

  # Telemetry
  Send_bip: bool

